version: "3"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/client
      - /client/node_modules
      - /client/.next
    ports:
      - 3000:3000
